#!/bin/bash
# postinst script for #PACKAGE#
#
# see: dh_installdeb(1)

set -e

dummy_package_folder=/tmp/Foam
mkdir ${dummy_package_folder}

setup_file="${dummy_package_folder}/setup.py"
foam_path=`python -c "import Foam; print Foam" | sed -e "s/<module 'Foam' from '//g" | sed -e "s/\/__init__.py'>//g"`

mv ${foam_path}/dummyFoam_setup.py ${setup_file}

(cd ${dummy_package_folder} && chmod 755 ./setup.py && sudo ./setup.py install)

rm -rf ${dummy_package_folder}

exit 0
